### ISSUE TITLE
addItemRowWithPrefixMiddle method parameter issue

### ISSUE THREAD

**Issue by rzbrth** [rocketbase-io/email-template-builder#3]
Hi, Could you please provide a way for addItemRowWithPrefixMiddle method to accept more than 4 parameter.
Instead of passing fixed number of params you can go for Map as method parameter so that we can bind data as per our need to the map and can pass the map as parameter into addItemRowWithPrefixMiddle method. In this way we won't have any constraint on number of params

**Comment by melistik** [comment]
hi @rzbrth, 
i've planned a rewrite especially for the table but don't know when i've enough free time for this feature.
Also some api changes are planned to get a bit smoother writing style...
Will comment this issue after some updates.

**Comment by rzbrth** [comment]
Thanks, I will be waiting for the release.

**Comment by melistik** [comment]
@rzbrth i've created a new release candidate that uses another template + extended the table features a lot. Would be great to get a feedback of you :)
