### ISSUE TITLE
Add maven repo in the Readme

### ISSUE THREAD

**Issue by bashizip** [rocketbase-io/email-template-builder#4]
Great work !! But I had to search all mvn to find out the [email-template-builder artifact. ](https://mvnrepository.com/artifact/io.rocketbase.commons/email-template-builder/1.6.0) and it seems outdated

**Comment by melistik** [comment]
Hi, i don't see the issue. also in the readme you've got a link to the [maven-repository](https://search.maven.org/artifact/io.rocketbase.mail/email-template-builder/2.0.0/jar)
